### ISSUE TITLE
GT Guidelines and OCR-D Wiki

### ISSUE THREAD

**Issue by tboenig** [OCR-D/ocrd-website#294] opened 2022-02-23 11:59 UTC
For questions, the GT guidelines are sometimes quite rigid. A link between the OCR-D Wiki and the Guidelines would be welcome.

# Steps

* [x] Development of a mechanism for the transfer of GT Wiki contributions to the GT Guidelines
* [x] Development and documentation as well as provision of a template for a GT Wiki submission
* [ ] put it on the website

**Comment by kba** [comment] 2023-04-25 13:06
Duplicate of #226

**Closed by kba** 2023-04-25 13:06 UTC
Labels: Epic, gt
